// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWUM0GNJqiPzRgpOdyVn2wURL1vjfSyyk',
    appId: '1:750934579693:web:716ddc5ef3c85df9926fe4',
    messagingSenderId: '750934579693',
    projectId: 'fitness-tracker-app886',
    authDomain: 'fitness-tracker-app886.firebaseapp.com',
    storageBucket: 'fitness-tracker-app886.firebasestorage.app',
    measurementId: 'G-DW55Y7ZXZN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVy1WlLMxzB3bzgCFwGlS1m0y7kvNJxFQ',
    appId: '1:750934579693:android:908219ee8a06e45f926fe4',
    messagingSenderId: '750934579693',
    projectId: 'fitness-tracker-app886',
    storageBucket: 'fitness-tracker-app886.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVkUaa3wtAvMm81zhtniW6dGiCmiQ5qO4',
    appId: '1:750934579693:ios:8f563647373d7341926fe4',
    messagingSenderId: '750934579693',
    projectId: 'fitness-tracker-app886',
    storageBucket: 'fitness-tracker-app886.firebasestorage.app',
    iosBundleId: 'com.example.fitnessTrackerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVkUaa3wtAvMm81zhtniW6dGiCmiQ5qO4',
    appId: '1:750934579693:ios:8f563647373d7341926fe4',
    messagingSenderId: '750934579693',
    projectId: 'fitness-tracker-app886',
    storageBucket: 'fitness-tracker-app886.firebasestorage.app',
    iosBundleId: 'com.example.fitnessTrackerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWUM0GNJqiPzRgpOdyVn2wURL1vjfSyyk',
    appId: '1:750934579693:web:3ee32105ca852075926fe4',
    messagingSenderId: '750934579693',
    projectId: 'fitness-tracker-app886',
    authDomain: 'fitness-tracker-app886.firebaseapp.com',
    storageBucket: 'fitness-tracker-app886.firebasestorage.app',
    measurementId: 'G-YHJ5J332ZL',
  );
}
